modLoader = "javafml"
loaderVersion = "[41,)"
license = "MPL-2.0"

[[mods]]
modId = "recursiveresources"
version = "${version}"
displayName = "Recursive Resources"
displayURL="https://github.com/TexTrueStudio/RecursiveResources"
logoFile= "icon.png"
credits="enjarai, chylex"
authors="TexTrue, TexTrueStudio, BocchiKessokuTeam"
description = '''
Enhances the Resource Pack menu by adding folder support for easier pack organization, ability to search packs by name or description, and new sorting options.
'''

[[dependencies.recursiveresources]]
modId = "forge"
mandatory = true
versionRange = "[41,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.recursiveresources]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19,)"
ordering = "NONE"
side = "BOTH"